--- #YAML:1.0
name:                FTN-Database
version:             0.17
abstract:            FTN SQL Database related operations for Fidonet/FTN related processing.
license:             perl
author:              
    - Robert James Clay <jame@rocasa.us>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::Tiny:                  0
    DBD::SQLite:                   0
    DBI:                           0
    File::Spec:                    0
    FTN::Log:                      0.02
    Getopt::Std:                   0
    Test::More:                    0
    Test::Pod:                     1.22
    Test::Pod::Coverage:           1.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
