--- #YAML:1.0
name:               FTN-Database
version:            0.25
abstract:           FTN SQL Database related operations for Fidonet/FTN related processing.
author:
    - Robert James Clay <jame@rocasa.us>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Tiny:         0
    DBD::SQLite:          0
    DBI:                  0
    File::Spec:           0
    FTN::Log:             0.02
    Getopt::Std:          0
    Test::More:           0
    Test::Pod:            1.22
    Test::Pod::Coverage:  1.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
